import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {catalog,Kind,Component,Circuit,State,colors,fmt,ports,create,demo,loadSensingDemo,isPilotLine,initial,step,remove} from './model';
import {Symbol,symbolBounds} from './Symbol';
import {orientation,placedPort,transformedBounds} from './layout';
import './style.css';
import {version} from '../package.json';
const groups:[string,Kind[]][]=[['Sources & storage',['tank','pump','variablePump','accumulator']],['Actuators',['cylinder','singleCylinder','motor']],['Directional valves',['valve22','valve32','valve42','valve43']],['Pressure & flow',['relief','reducing','restriction','flowControl','check','filter']],['Compensation & load sensing',['compensator','compensatedFlow','lsBypass','shuttle']],['Measurement & utilities',['gauge','meter','junction','cap']]];
function App(){
 const [c,setC]=useState<Circuit>(demo);const [s,setS]=useState<State>(initial);const [running,setRunning]=useState(false);const [speed,setSpeed]=useState(1);const [selected,select]=useState<string|null>(null);const [view,setView]=useState({x:0,y:0,z:1});const [wire,setWire]=useState<{from:string;x:number;y:number}|null>(null);const [hover,setHover]=useState<string|null>(null);
 const svg=useRef<SVGSVGElement>(null);const sim=useRef(s);const circuit=useRef(c);const interaction=useRef<{id:string;x:number;y:number;ox:number;oy:number}|null>(null);const time=useRef(0);const [phase,setPhase]=useState(0);
 circuit.current=c;sim.current=s;
 useEffect(()=>{setS(old=>step(c,old,0))},[c]);
 useEffect(()=>{if(!running)return;let frame=0,last=performance.now();const tick=(now:number)=>{const dt=Math.min(0.05,(now-last)/1000)*speed;last=now;const next=step(circuit.current,sim.current,dt);sim.current=next;setS(next);time.current+=dt;setPhase(time.current);frame=requestAnimationFrame(tick)};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame)},[running,speed]);
 const erase=()=>{if(selected){setC(old=>remove(old,selected));select(null)}};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if((e.target as HTMLElement).closest('input,select,textarea'))return;if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();erase()}if(e.key==='Escape'){setWire(null);interaction.current=null;select(null)}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[selected]);
 const point=(clientX:number,clientY:number)=>{const r=svg.current!.getBoundingClientRect();return {x:(clientX-r.left-view.x)/view.z,y:(clientY-r.top-view.y)/view.z}};
 const endpoint=(key:string)=>{const [id,name]=key.split(':');const o=c.components.find(o=>o.id===id);const raw=o&&ports(o.kind).find(p=>p.name===name);const p=o&&raw?placedPort(o,raw):undefined;return o&&p?{x:o.x+p.x,y:o.y+p.y,nx:p.nx,ny:p.ny}:{x:0,y:0,nx:0,ny:0}};
 const route=(a:{x:number;y:number;nx?:number;ny?:number},b:{x:number;y:number;nx?:number;ny?:number})=>{
  const ax=a.x+(a.nx||0)*24,ay=a.y+(a.ny||0)*24,bx=b.x+(b.nx||0)*24,by=b.y+(b.ny||0)*24;
  const start=`M${a.x} ${a.y}L${ax} ${ay}`;let middle;
  if(a.ny&&b.ny){if(a.ny*(by-ay)<0||b.ny*(ay-by)<0){const x=ax===bx?ax+70:(ax+bx)/2;middle=`H${x}V${by}H${bx}`}else{const y=(ay+by)/2;middle=`V${y}H${bx}V${by}`}}
  else if(a.nx&&b.ny)middle=`V${by}H${bx}`;
  else if(a.ny&&b.nx)middle=`H${bx}V${by}`;
  else{const x=(ax+bx)/2;middle=`H${x}V${by}H${bx}`}
  return `${start}${middle}L${b.x} ${b.y}`;
 };
 const update=(o:Component,key:string,value:number|string|boolean)=>setC(old=>({...old,components:old.components.map(x=>x.id===o.id?{...x,p:{...x.p,[key]:value,...(key==='bore'&&typeof value==='number'?{rod:Math.min(Number(x.p.rod),value*0.95)}:{})}}:x)}));
 const changeLayout=(o:Component,change:Partial<Pick<Component,'rotation'|'flipX'|'flipY'>>)=>setC(old=>({...old,components:old.components.map(x=>x.id===o.id?{...x,...change}:x)}));
 const flipKey=(o:Component,horizontal:boolean):'flipX'|'flipY'=>((o.rotation||0)%180===90)!==horizontal?'flipX':'flipY';
 const bounds=(o:Component)=>transformedBounds(o,symbolBounds(o));
 const chosen=c.components.find(o=>o.id===selected);const selectedLine=c.lines.find(l=>l.id===selected);
 const add=(kind:Kind,x?:number,y?:number)=>{const r=svg.current!.getBoundingClientRect();const center=point(r.left+r.width/2,r.top+r.height/2);const o=create(kind,Math.round((x??center.x)/10)*10,Math.round((y??center.y)/10)*10);setC(old=>({...old,components:[...old.components,o]}));select(o.id)};
 const reset=()=>{setS(initial());sim.current=initial();setPhase(0);setS(step(c,initial(),0))};
 const fit=()=>{if(!svg.current)return;const r=svg.current.getBoundingClientRect();const xs=c.components.map(o=>o.x),ys=c.components.map(o=>o.y);const minX=Math.min(50,...xs)-100,minY=Math.min(0,...ys)-80;const w=Math.max(850,...xs)-minX+140,h=Math.max(550,...ys)-minY+100;const z=Math.min(1.4,r.width/w,r.height/h);setView({z,x:(r.width-w*z)/2-minX*z,y:(r.height-h*z)/2-minY*z})};
 useEffect(()=>{fit()},[]);
 const portReading=(o:Component,name:string)=>s.ports[o.id+':'+name]?.pressure||0;
 const componentFlow=(o:Component)=>{const reads=c.lines.filter(l=>l.from.startsWith(o.id+':')||l.to.startsWith(o.id+':')).map(l=>Math.abs(s.lines[l.id]?.flow||0));return Math.max(0,...reads)};
 const numeric=(o:Component,key:string,label:string,min=0,max=100000,increment=1)=><label className="field" key={key}>{label}<input type="number" min={min} max={max} step={increment} value={Number(o.p[key])} onChange={e=>update(o,key,Math.max(min,Math.min(max,Number(e.currentTarget.value))))}/></label>;
 const valveControls=(o:Component)=><div className="spool">{(o.kind==='valve22'||o.kind==='valve32'?[0,1]:o.kind==='valve42'?[-1,1]:[-1,0,1]).map(pos=><button key={pos} className={Number(o.p.position)===pos?'active':''} onClick={()=>update(o,'position',pos)}>{o.kind==='valve22'?(pos?'Open':'Closed'):o.kind==='valve32'?(pos?'Supply':'Return'):pos<0?'Retract':pos>0?'Extend':'Neutral'}</button>)}</div>;
 return <div className="app"><header><div className="brand"><span className="brandmark">H</span><div><strong>HydroSim</strong><span className="version">v{version}</span><small>HYDRAULIC TRAINING BENCH</small></div></div><div className="toolbar"><button className={running?'':'primary'} onClick={()=>setRunning(!running)}>{running?'Ⅱ Pause':'▶ Run'}</button><button onClick={reset}>Reset simulation</button><label>Speed <select aria-label="Simulation speed" value={speed} onChange={e=>setSpeed(Number(e.currentTarget.value))}>{[0.25,0.5,1,2,4].map(x=><option key={x} value={x}>{x}×</option>)}</select></label><span className="separator"/><button onClick={()=>{setC(demo());select(null);sim.current=initial();setS(initial());setView({x:0,y:0,z:1});setTimeout(fit,0)}}>Load demo</button><button onClick={()=>{setC(loadSensingDemo());select(null);sim.current=initial();setS(initial());setView({x:0,y:0,z:1});setTimeout(fit,0)}}>Load LS demo</button><button onClick={()=>{setC({components:[],lines:[]});select(null);setS(initial())}}>Clear circuit</button></div><span className="runstatus"><i className={running?'live':''}/>{running?'SIMULATING':'PAUSED'}</span></header>
 <main><aside className="palette"><div className="panel-title">COMPONENT LIBRARY</div><p className="muted">Drag onto the canvas, or click to add.</p>{groups.map(([title,kinds])=><section key={title}><h3>{title}</h3>{kinds.map(kind=><button key={kind} draggable onDragStart={e=>e.dataTransfer!.setData('hydraulic/component',kind)} onClick={()=>add(kind)}><span className="mini">{kind==='tank'?'⊔':kind==='pump'||kind==='variablePump'?'◯':kind.startsWith('valve')?'▭':kind.includes('Cylinder')||kind==='cylinder'?'⊞':kind==='junction'?'┴':'◇'}</span>{catalog[kind]}</button>)}</section>)}<div className="palette-note">Educational approximation<br/>US customary units</div></aside>
 <div className="workspace"><div className="canvasbar"><span>{wire?'CONNECTING · Drag to another port':`${c.components.length} components · ${c.lines.length} connections`}</span><div><button onClick={()=>setView(v=>({...v,z:Math.max(0.3,v.z/1.2)}))}>−</button><span>{Math.round(view.z*100)}%</span><button onClick={()=>setView(v=>({...v,z:Math.min(2.5,v.z*1.2)}))}>+</button><button onClick={fit}>Fit circuit</button></div></div>
 <svg ref={svg} className="canvas" aria-label="Hydraulic schematic canvas" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const k=e.dataTransfer!.getData('hydraulic/component') as Kind;if(k in catalog){const p=point(e.clientX,e.clientY);add(k,p.x,p.y)}}}
 onWheel={e=>{const r=svg.current!.getBoundingClientRect();const px=e.clientX-r.left,py=e.clientY-r.top;const z=Math.max(0.3,Math.min(2.5,view.z*(e.deltaY>0?0.9:1.1)));setView({z,x:px-(px-view.x)*z/view.z,y:py-(py-view.y)*z/view.z})}}
 onPointerDown={e=>{if(e.target===e.currentTarget||(e.target as Element).classList.contains('grid-bg')){select(null);setWire(null);interaction.current={id:'pan',x:e.clientX,y:e.clientY,ox:view.x,oy:view.y};e.currentTarget.setPointerCapture(e.pointerId)}}}
 onPointerMove={e=>{const p=point(e.clientX,e.clientY);if(wire){setWire({...wire,...p});const target=document.elementFromPoint?.(e.clientX,e.clientY)?.getAttribute('data-port');setHover(target&&target!==wire.from?target:null)}const d=interaction.current;if(!d)return;if(d.id==='pan')setView(v=>({...v,x:d.ox+e.clientX-d.x,y:d.oy+e.clientY-d.y}));else setC(old=>({...old,components:old.components.map(o=>o.id===d.id?{...o,x:Math.round((d.ox+p.x-d.x)/10)*10,y:Math.round((d.oy+p.y-d.y)/10)*10}:o)}))}}
 onPointerUp={e=>{interaction.current=null;if(wire){const target=document.elementFromPoint(e.clientX,e.clientY)?.getAttribute('data-port');if(target&&target!==wire.from&&!c.lines.some(l=>(l.from===wire.from&&l.to===target)||(l.to===wire.from&&l.from===target)))setC(old=>({...old,lines:[...old.lines,{id:`l${Date.now()}`,from:wire.from,to:target}]}));setWire(null);setHover(null)}}}>
 <defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><circle cx="0" cy="0" r="0.9" fill="#cdd6df"/></pattern><marker id="arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto-start-reverse"><path d="M0 0L10 5L0 10Z" fill="#263543"/></marker></defs>
 <rect className="grid-bg" width="100%" height="100%" fill="#f8fafc"/>
 <g transform={`translate(${view.x},${view.y}) scale(${view.z})`}><rect className="grid-bg" x="-10000" y="-10000" width="20000" height="20000" fill="url(#grid)"/>
 {c.lines.map(l=>{const r=s.lines[l.id]||{flow:0,pressure:0,color:'inactive'};const a=endpoint(l.from),b=endpoint(l.to);const d=route(a,b);return <g key={l.id} className="hose" onPointerDown={e=>{e.stopPropagation();select(l.id)}}><title>{fmt(r.pressure)} PSI · {fmt(Math.abs(r.flow))} GPM · {r.flow<0?'reverse':'forward'}{Math.abs(r.flow)<0.001?' · static':''}</title><path d={d} stroke="transparent" strokeWidth="16" fill="none"/><path d={d} stroke={selected===l.id?'#142a44':colors[r.color]} strokeWidth={selected===l.id?5:3} strokeDasharray={isPilotLine(c,l)?'6 4':undefined} fill="none"/>{Math.abs(r.flow)>0.001&&<path d={d} stroke="white" strokeWidth="2" strokeDasharray="2 19" strokeDashoffset={-phase*Math.sign(r.flow)*(16+Math.min(15,Math.abs(r.flow))*5)} fill="none"/>}<text className="line-value" x={(a.x+b.x)/2+7} y={(a.y+b.y)/2-8}>{selected===l.id?`${fmt(r.pressure)} PSI · ${fmt(Math.abs(r.flow))} GPM`:''}</text></g>})}
 {wire&&<path d={route(endpoint(wire.from),wire)} stroke={hover?'#289967':'#487da9'} strokeWidth="2.5" fill="none" strokeDasharray="6 4"/>}
 {c.components.map(o=><g key={o.id} transform={`translate(${o.x},${o.y})`} className="component" data-component={o.label} onPointerDown={e=>{e.stopPropagation();select(o.id);const p=point(e.clientX,e.clientY);interaction.current={id:o.id,...p,ox:o.x,oy:o.y};svg.current!.setPointerCapture(e.pointerId)}}>
 <g className="component-geometry" transform={orientation(o)}><rect className="component-hit" {...symbolBounds(o)} fill="transparent" stroke={selected===o.id?'#5482aa':'none'} strokeDasharray="4 3"/><Symbol o={o} s={s}/></g><text className="component-label" x="0" y={Math.min(-43,bounds(o).y-14)}>{o.label}</text>
 {o.kind==='meter'&&<text className="instrument-overlay" y={Math.min(-38,bounds(o).y-4)}>{fmt(componentFlow(o))} GPM</text>}
 {ports(o.kind).map(raw=>{const p=placedPort(o,raw);const key=o.id+':'+p.name;return <g key={p.name}><text className="port-label" x={p.x+(p.nx?p.nx*13:13)} y={p.y+(p.ny?p.ny*13:0)+4}>{p.name}</text><circle data-port={key} aria-label={`${o.label} port ${p.name}`} cx={p.x} cy={p.y} r={wire?8:6} className={`port ${wire?'compatible':''} ${hover===key||wire?.from===key?'port-active':''}`} onPointerEnter={()=>setHover(key)} onPointerLeave={()=>setHover(null)} onPointerDown={e=>{e.stopPropagation();const q=point(e.clientX,e.clientY);interaction.current=null;setWire({from:key,...q});svg.current!.setPointerCapture(e.pointerId)}}><title>{p.name} · {fmt(portReading(o,p.name))} PSI · Drag to connect</title></circle></g>})}
 {o.kind.startsWith('valve')&&<foreignObject x="-75" y={Math.max(65,bounds(o).y+bounds(o).height+26)} width="150" height="30"><div className="inline-controls" onPointerDown={e=>e.stopPropagation()}>{valveControls(o)}</div></foreignObject>}
 </g>)}
 </g></svg>
 <div className="legend">{Object.entries(colors).map(([k,v])=><span key={k}><i style={{background:v}}/>{k==='pressure'?'Pressure':k==='return'?'Return':k==='suction'?'Suction':k==='metered'?'Metered':k==='reduced'?'Reduced':'Inactive'}</span>)}<span className="flow-key">Moving dots = flowing oil</span></div><div className="canvas-help">Drag ports to connect · Drag components to move · Drag empty canvas to pan · Scroll to zoom · Delete to remove</div>
 </div>
 <aside className="inspector"><div className="panel-title">{chosen?'COMPONENT INSPECTOR':selectedLine?'CONNECTION INSPECTOR':'TRAINING GUIDE'}</div>{chosen?<><h2>{catalog[chosen.kind]}</h2><label className="field">Label<input value={chosen.label} onChange={e=>{const label=e.currentTarget.value;setC(old=>({...old,components:old.components.map(o=>o.id===chosen.id?{...o,label}:o)}))}}/></label><h3>Layout</h3><div className="layout-controls"><button onClick={()=>changeLayout(chosen,{rotation:((chosen.rotation||0)+270)%360})}>Rotate left</button><button onClick={()=>changeLayout(chosen,{rotation:((chosen.rotation||0)+90)%360})}>Rotate right</button><button className={chosen[flipKey(chosen,true)]?'active':''} aria-pressed={!!chosen[flipKey(chosen,true)]} onClick={()=>changeLayout(chosen,{[flipKey(chosen,true)]:!chosen[flipKey(chosen,true)]})}>Flip horizontal</button><button className={chosen[flipKey(chosen,false)]?'active':''} aria-pressed={!!chosen[flipKey(chosen,false)]} onClick={()=>changeLayout(chosen,{[flipKey(chosen,false)]:!chosen[flipKey(chosen,false)]})}>Flip vertical</button><button onClick={()=>changeLayout(chosen,{rotation:0,flipX:false,flipY:false})}>Reset orientation</button></div><h3>Live readings</h3><div className="readings">{ports(chosen.kind).map(p=><div key={p.name}><span>{p.name} pressure</span><strong>{fmt(portReading(chosen,p.name))} PSI</strong></div>)}<div><span>Flow</span><strong>{fmt(componentFlow(chosen))} GPM</strong></div>{['cylinder','singleCylinder'].includes(chosen.kind)&&<><div><span>Extension</span><strong>{fmt((s.motion[chosen.id]?.position||0)*Number(chosen.p.stroke))} in</strong></div><div><span>Velocity</span><strong>{fmt(s.motion[chosen.id]?.speed||0)} in/s</strong></div></>}{chosen.kind==='variablePump'&&<div><span>Swashplate stroke</span><strong>{fmt((s.stroke[chosen.id]||0)*100)}%</strong></div>}{chosen.kind==='shuttle'&&<div><span>Selected inlet</span><strong>{s.selected[chosen.id]||'A'}</strong></div>}{['compensator','lsBypass'].includes(chosen.kind)&&<div><span>Pressure margin</span><strong>{fmt(Math.max(0,portReading(chosen,chosen.kind==='compensator'?'B':'P')-portReading(chosen,'X')))} PSI</strong></div>}{chosen.kind==='motor'&&<><div><span>Speed</span><strong>{fmt(s.motion[chosen.id]?.rpm||0)} RPM</strong></div><div><span>Pressure difference</span><strong>{fmt(Math.abs(portReading(chosen,'A')-portReading(chosen,'B')))} PSI</strong></div></>}{chosen.kind==='accumulator'&&<div><span>Charge</span><strong>{fmt((s.motion[chosen.id]?.charge||0)*100)}%</strong></div>}{chosen.kind==='meter'&&<div><span>Direction</span><strong>{componentFlow(chosen)<0.001?'No flow':(s.ports[chosen.id+':A']?.pressure||0)>=(s.ports[chosen.id+':B']?.pressure||0)?'A → B':'B → A'}</strong></div>}</div><h3>Operating settings</h3>
 {['pump','variablePump'].includes(chosen.kind)&&<><button className="wide" onClick={()=>update(chosen,'running',!chosen.p.running)}>{chosen.p.running?'Stop pump':'Start pump'}</button>{numeric(chosen,'flow','Available flow (GPM)',0,100,0.1)}{numeric(chosen,'maxPressure','Maximum pressure (PSI)',1,10000)}{chosen.kind==='variablePump'&&<>{numeric(chosen,'minStroke','Minimum stroke (%)',0,100,0.1)}{numeric(chosen,'pilotStart','Pilot start pressure (PSI)',0,10000)}{numeric(chosen,'pilotFull','Full stroke pilot pressure (PSI)',1,10000)}<p className="muted">Connect X to control stroke with pilot pressure. Stroke follows pilot pressure between these pressures, subject to the minimum stroke. A nonzero minimum lets the pump supply its own pilot. Unconnected X uses full manual stroke; available flow sets the full-stroke output.</p></>}</>}
 {chosen.kind.startsWith('valve')&&<><label className="field">Spool position</label>{valveControls(chosen)}{chosen.kind==='valve43'&&<label className="field">Center condition<select value={String(chosen.p.center)} onChange={e=>update(chosen,'center',e.currentTarget.value)}>{['closed','open','tandem','float'].map(x=><option key={x} value={x}>{x} center</option>)}</select></label>}</>}
 {['relief','reducing'].includes(chosen.kind)&&numeric(chosen,'setting',chosen.kind==='relief'?'Relief setting (PSI)':'Reduced pressure (PSI)',1,10000)}
 {['compensator','lsBypass','compensatedFlow'].includes(chosen.kind)&&<>{numeric(chosen,'margin','Compensation margin (PSI)',1,2000)}{chosen.kind==='compensator'&&<label className="field">Reverse-flow bypass<select value={chosen.p.reverseCheck?'on':'off'} onChange={e=>update(chosen,'reverseCheck',e.currentTarget.value==='on')}><option value="on">Check valve enabled</option><option value="off">Blocked reverse flow</option></select></label>}<p className="muted">{chosen.kind==='compensator'?'A → B regulator: holds B near X plus the margin. Place ahead of a metering restriction; connect X after the restriction.':chosen.kind==='lsBypass'?'P → T bypass: diverts excess flow when supply exceeds X plus the margin. Connect X to the highest load signal; use a separate safety relief.':'A → B metered flow stays near its setting when sufficient pressure is available. Low pressure or pump starvation reduces flow.'}</p></>}
 {chosen.kind==='shuttle'&&<p className="muted">Selects the higher-pressure A or B inlet for C; isolates the lower-pressure inlet. Equal pressures select A. Connect C to X for a load-sensing pilot network.</p>}
 {['flowControl','restriction','compensatedFlow'].includes(chosen.kind)&&<>{numeric(chosen,'limit',chosen.kind==='restriction'?'Nominal flow (GPM)':'Flow limit (GPM)',0,100,0.1)}{chosen.kind==='restriction'&&numeric(chosen,'referenceDrop','Nominal pressure drop (PSI)',1,2000)}<input aria-label="Flow limit slider" type="range" min="0" max="12" step="0.1" value={Number(chosen.p.limit)} onChange={e=>update(chosen,'limit',Number(e.currentTarget.value))}/></>}
 {['cylinder','singleCylinder'].includes(chosen.kind)&&<>{numeric(chosen,'bore','Bore (in)',0.1,24,0.1)}{chosen.kind==='cylinder'&&numeric(chosen,'rod','Rod diameter (in)',0,Number(chosen.p.bore)*0.95,0.1)}{numeric(chosen,'stroke','Stroke (in)',0.1,120,0.1)}{numeric(chosen,'load','Resisting load (lbf)',0,100000)}</>}
 {chosen.kind==='motor'&&<>{numeric(chosen,'displacement','Displacement (in³/rev)',0.1,100,0.1)}{numeric(chosen,'load','Resisting torque (lbf·in)',0,100000)}</>}
 {chosen.kind==='accumulator'&&<>{numeric(chosen,'precharge','Precharge (PSI)',1,10000)}{numeric(chosen,'capacity','Oil capacity (in³)',1,1000)}</>}
 {['tank','gauge','meter','junction','cap','filter','check'].includes(chosen.kind)&&<p className="muted">{chosen.kind==='check'?'Permits A → B flow; blocks reverse flow.':chosen.kind==='cap'?'A sealed termination. Pressure can build; oil cannot pass.':'Passive component. Readings follow the connected circuit.'}</p>}
 <button className="danger wide" onClick={erase}>Delete component</button></>:selectedLine?<><h2>Hydraulic line</h2><div className="readings"><div><span>Pressure</span><strong>{fmt(s.lines[selectedLine.id]?.pressure||0)} PSI</strong></div><div><span>Flow</span><strong>{fmt(Math.abs(s.lines[selectedLine.id]?.flow||0))} GPM</strong></div><div><span>State</span><strong>{s.lines[selectedLine.id]?.color}</strong></div></div><p className="muted">{selectedLine.from} → {selectedLine.to}<br/>Crossing lines do not connect. Use a junction to create a branch.</p><button className="danger wide" onClick={erase}>Delete connection</button></>:<><h2>Follow the oil.</h2><p>Build a circuit, operate its valves, and see how flow and load create pressure.</p><div className="guide"><h3>{c.components.some(o=>o.kind==='lsBypass')?'Try load sensing':'Try the demonstration'}</h3>{c.components.some(o=>o.kind==='lsBypass')?<ol><li>Press <b>Run</b>. VP1 runs at minimum stroke; LS1 bypasses standby flow.</li><li>Select <b>Extend</b> on DCV1. OR1 meters about 3.0 GPM.</li><li>Change <b>CYL1</b> load. Supply pressure and VP1 stroke respond while metered flow stays steady.</li><li>Change <b>OR1</b> nominal flow to adjust extension speed.</li><li>Inspect <b>PC1</b> margin and <b>SH1</b> selected inlet. Retract switches the load signal.</li><li>At full stroke, RV1 limits pressure. Retraction bypasses PC1 through its reverse check.</li></ol>:<ol><li>Press <b>Run</b>. The tandem center sends pump flow back to tank.</li><li>Select <b>Extend</b> below DCV1. Watch the cylinder and return path.</li><li>Select <b>FC1</b> and reduce its flow limit. The cylinder slows.</li><li>At full stroke, watch <b>RV1</b> relieve at 1,500.0 PSI.</li><li>Select <b>Retract</b> to reverse the work ports.</li></ol>}</div><p className="muted">Select a component to edit its label, adjust settings, and inspect live readings. Pressure without moving dots means static oil.</p><div className="tip">The demo pump is enabled. Run/Pause controls simulation time; the pump has its own start/stop control.</div></>}
 </aside></main></div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
